### ISSUE TITLE
Card readers can be scramble after a restart of the writer

### ISSUE THREAD

**Issue by kelson42** [offspot/cardshop#169]
This leads to a lot of confusion for the operator who needs after each restart to make a new reaffectation of USB flash drives slots to be sure it fits (to his stickers). See #168

**Comment by kelson42** [comment]
I have a few questions:
* Why not reseting the configuration if the values are not the same as before (the reboot)
* Do the identical serial affect all the USB flash drive readers?

**Comment by rgaudin** [comment]
It's not a configuration issue, the problem is being able to label the slots on the outside physical slots so the operator knows which one is which.
If we can't recognize devices we can't detect configuration has changed.

Regarding devices, I couldn't find any with different serials and the one we are using are already high end ones (for general public).

I imagine the dedicated HW from belena handles this correctly though.

**Comment by kelson42** [comment]
Yes, but the writer configuration is responsible for labeling the devices... so if the system changes things behind then the labelling has no value anymore and this part of the configuration should be reseted.

**Comment by kelson42** [comment]
After discussion with @rgaudin:
* For each device we need to have an unique identifier as good as possible
* If not possible to distinguish 2+ devices, then it should be forbidden to use these devices
* None distinguisable devices should somehow visible in the configuration tool
* If after a reboot, a label can not be mapped properly anymore to a devices (because this device is not distinguishable anymore) then an email should be sent to the writer operator

**Comment by kelson42** [comment]
The writer piece of code has been deprecated (an removed from the code base) as part of Kiwix Hotspot 3.0 development. Therefore this issue became purposeless and has been closed. It might be reconsidered at some point if decide to revive the writer.
