### ISSUE TITLE
System accepts payment but does not create account (nor emails the user with credentials)

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#295]
I've seen this happen twice already this week that a user would pay for either a pre-configured image download or a full cardshop access, and they would not receive the email (both have checked their spam folder and nothing to see). In the case of the cardshop person, the payment has been recorded on Stripe but no account was created. 

They had a "+" sign in their email address, e.g. `toto+kiwix@email.com` but not the guy with the wikipedia download so I'm not sure it's related to the special character.

**Comment by rgaudin** [comment]
Can you please transfer the details via another channel so this can be investigated?

**Comment by rgaudin** [comment]
Brief recap:

- our webhook has been removed from Stripe about a year ago. I have no idea why. Probably a manual error from either one of us.
- Because there was no webhook call, none of our users received a receipt. They would be greated with the download details or access credentials upon payment, but no email was sent.
- that explains why the person ordering an image did not get an email… nobody did. You had to click the download link right after payment. Same goes for credentials. you had to copy/use the directly.
- As for the cardshop access, it was apparently paid-for during a cardshop maintenance. That case was not planned for an thus the feedback page failed.

Both issues are now fixed
