### ISSUE TITLE
File happens in configuration listing while absent from ideascube.yml

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#297]
`deployed_medicine-2022-03.zim` was deleted on March 18 and cannot indeed be found in https://download.kiwix.org/library/ideascube.yml
It is also nowhere to be found in download.kiwix.org/zim

Yet I can see it offered in the cardshop - how is this possible? 
![image](https://user-images.githubusercontent.com/21675885/159369902-91daee8a-9ebc-4823-ac84-7cd0eb84f4c3.png)

**Comment by kelson42** [comment]
I confirm, it is not in the libraries at https://download.kiwix.org/library/. Looks like a cache problem.

**Comment by rgaudin** [comment]
Yes, it's a cache issue that we've faced in the past. For some reason, the refresh code triggers a Kill by the system. When it happens, the only solution is to restart the container (which I did now).

It looks resources related as when it happens, even running an ipython shell instead of a bare python shell is being killed… but the stats returned by `sloppy stats` shows plenty of available RAM (and CPU).
Seems to be more frequent now that we backup databases but I'm not sure.
We'll look at this code when we have a chance but it's hotspot code that will eventually be replaced wih OPDS. Could be image or hosting related as well.

Keeping that open until root cause it identified and fixed.
