### ISSUE TITLE
Upload is stalled

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#317]
I'm looking at order [L1239R63EC](https://cardshop.hotspot.kiwix.org/all-orders/63ec71983c58c81484573e21) and it looks like it's still uploading the image after 48 hours.

Any idea what happened?

**Comment by rgaudin** [comment]
The cardshop was offline during a less than an hour on Wednesday (a change you requested let to an outage that needed fixing). It looks like the worker could not not inform that it completed uploading because it was gone.

I am sending you the link to the image ; You can either use it or cancel this task and recreate it.
