### ISSUE TITLE
JSON-included logo not imported

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#322]
How to reproduce:
- Download config which includes a logo in it
- (optional) Open JSON and see that there is a `data` field with code 
![image](https://github.com/offspot/cardshop/assets/21675885/be7abc6b-5320-4ab8-acdb-0c52c01f58c6)
- Import config
- Image is missing

**Comment by rgaudin** [comment]
I can't reproduce. Might be related to the actual logo and/or JSON export. Can you please share it with me?

**Comment by Popolechien** [comment]
Done via Slack.

**Comment by rgaudin** [comment]
Thank you ; it's a side effect of #225. Because we don't check the file format of uploaded logo, we end up with a JPEG logo (that works on the box currently) while we should only accepts PNG (#214).
We thus export the JSON file with the JPEG image inside but when we import a JSON, we check the file format (🤷‍♂️) and silently remove non-expected format.

I am closing this in favor of #225 and #214
