### ISSUE TITLE
Remove "Preloaded file resources" field and move file manager as option in General tab

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#375]
Seeing how #373 is closed as duplicate of #106 which is itself 4 years old, I would suggest ignoring #372 and simply add a "Include external files manager" button in the General tab along with the metrics option. The external URL with a zip thing is too tedious and confusing at this stage.

Of course if there are plans to include direct upload short term then this issue should be ignored.

**Comment by rgaudin** [comment]
File upload is what we want to do ultimately but comes with a lot of constraints:
- Is there a filesize maximum? Then what is it?
  - this has consequences on where it can be uploaded to
  - storing GBs makes sense here. that's what we had with WikiFundi (which drove the feature)
- Storing at third parties is expensive as Wasabi for instance bills every byte for 30d
- ATM we only support publicly reachable uploads (we could support otherwise in image-creator should the need arise) making us responsible for uploaded content (can be abused to share illegal stuff)
- UI would be a challenge. Uploading large files takes time ; needs feedback, potentially blocking the UI. etc. Uploading many files instead or a single ZIP is probably more convenient.

For all those reasons, a URL field to a [grosfichiers](https://www.grosfichiers.com/) or [wetrasnfer](https://wetransfer.com/) seemed like a reasonable alternative.

I don't think file upload will happen before we redo the CS UI.

I don't think we should get rid of the feature because it's very important for some use cases. I imagine users who don't understand or can't use it because it's too difficult just leave it out.

So, should we move “Include external files manager” and the URL field to General?

**Comment by Popolechien** [comment]
Very good points. I still think that the default assumption is that we don't want to confuse users with choices they don't know how to handle.
 
We could put a maximum at 300 MB - that's a fairly small upload/storage volume and would allow for PDF files, APKs, etc. If people want to add more (e.g. Movies) then they can do it once the image has been installed.

For the time being I'd move it to General as a radio button "External files manager" and change the URL field description to _"File manager allows import of external files to the hotspot. You can preload them here by indicating the URL of a ZIP file containing your resources"_ 
Seems like a lot of text so probably will be a row by itself.

**Comment by rgaudin** [comment]
Moved to General. Also added checks on the URL fields to prevent human mistakes
